### ISSUE TITLE
Change permissions to user only at bootstrap

### ISSUE THREAD

**Issue by sethiele** [awendt/poet#14]
After running `poet bootstrap` the folder permissions of `~/.ssh/config.d` is `rwxr-xr-x` (755) but should be (IMO) `rwx------` (700).

Bonus: Maybe the bootstrap can change the `~/.ssh` directory also to 700 (after requesting permissions)?

**Comment by awendt** [comment]
This is an excellent idea! I'm currently working on making the code more accessible to contributors and will post a checklist once that is merged.

**Comment by awendt** [comment]
this depends on #16

**Comment by awendt** [comment]
Closing because I'm going to stop maintaining this project.
